cervezas_homepage:
    path:     /
    defaults: { _controller: cervezasBundle:Default:index }
cervezas_Id:
    path:     /id/{id}
    defaults: { _controller: cervezasBundle:Default:id }
cervezas_crear:
    path:     /crear/{nombre}/{pais}
    defaults: { _controller: cervezasBundle:Default:crear }
cervezas_Form:
    path:     /form
    defaults: { _controller: cervezasBundle:Default:form }
cervezas_Mod:
    path:     /mod/{id}
    defaults: { _controller: cervezasBundle:Default:mod }
